### ISSUE TITLE
I Think I Find Bug

### ISSUE THREAD

**Issue by Deadlyhacker** [Zyg0te/Locker#7]
What happens if ı delete This application from my device by TWRP or from /Data/App ?

Boot into recovery
Open Recovery File manager
GoTo Data/App/
Delete Application.apk
Done
Reboot

**Comment by Zyg0te** [comment]
Not sure what would happen but I'm assuming you'd disable the lock screen
protection.

However this is not a bug. If you install TWRP then anyone with physical
access to your decide has root access to your phone anyway so there is no
real need to bypass the lock screen.

However, if you want to mitigate this vulnerability you can enable full
disk encryption. You'd then have to unlock the device first before TWRP is
able to delete any system files.

On Sunday, 13 March 2016, Deadlyhacker <notifications@github.com> wrote:

> What happens if ı delete This application from my device by TWRP or from
> /Data/App ?
>
> Boot into recovery
> Open Recovery File manager
> GoTo Data/App/
> Delete Application.apk
> Done
> Reboot
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Zyg0te/Locker/issues/7>.
>


-- 
Edvard;

**Comment by Deadlyhacker** [comment]
Thanks for quick feedback :)

**Comment by Zyg0te** [comment]
No problem. Cheers!

**Comment by JasperWeiss** [comment]
@Zyg0te Actually that's not really the case. When you enter TWRP it'll ask for the password, simply hit cancel and you're in. (You just can't read the /data partition)

**Comment by Zyg0te** [comment]
@JasperWeiss You're absolutely right. Still, when keeping your bootloader unlocked and flashing custom recovery images, you should be aware of the consequences in terms of security. Without going on too big of a rant, this is one of the biggest issues I have with Android as and end-user. Anything other than stock Android is terrible, which means that on non-Nexus devices, you will have to compromise security in order to get a proper Android experience (imo obviously). The second you unlock your bootloader, verified boot goes out the window.

**Comment by JasperWeiss** [comment]
Exactly, for security reasons I prefer to use Cyanogenmod instead of some proprietary ROM. But that means I need to give up physical security. Having the boot loader locked with a password on TWRP wouldn't work either. Because it would render the phone useless if you forget the password.
Perhaps it would work if there's a 'forgot password' option that wipes the data, resets that recovery password and unlocks the bootloader.

**Comment by Zyg0te** [comment]
I totally agree. However, again, by unlocking the bootloader and modifying the system partition basically means you wave off the protection that [verified boot](https://source.android.com/security/verifiedboot/) provides which is a great protection mechanism. On the other hand, especially on older devices, you're missing out on a several security mechanisms if you're running and older version of Android, in which case, it might become a worthwile trade-off in terms of security.

**Comment by JasperWeiss** [comment]
Hmmm yes, it's a complicated situation. For me, there's also the problem of having Google completely own the ROM. But I guess installing GAPPS as system apps have the same effect.
